### ISSUE TITLE
Angle tracking and cleanup

### ISSUE THREAD

**Issue by nic-barbara** [dazzmo/CassieControllers#24]
We need to add a task for tracking angles, and we need to clean up the existing code/docs to make it easier to use. Remaining things to fix up are:

- [ ] Add angle-tracking tasks (generic).
- [ ] Add task to Cassie sim to keep pelvis at desired orientation (could be controlled with joystick later).
- [ ] See if we still need the joint damping task.
- [ ] Tune controller gains (methodically).
- [ ] Update `README.md` for Cassie examples.

**Comment by dazzmo** [comment]
New [damotion](https://github.com/dazzmo/damotion) library's control module now addresses these tasks, with demonstrations shown in the cassie examples in 5b90119a7c6fc99693b3371f4994a8659659f221.
